### ISSUE TITLE
Add "Download" type for general downloads page

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#139]
or maybe this a "Link" (similar to type "Repository") ?

what do you think @hansioan 

for an example see http://slimsuite.blogspot.com/p/downloads.html

**Comment by hansioan** [comment]
Many tools have a download page, some perhaps with instructions and we use Downloads source code, or binaries or source package etc.

If the download urls were intended for linking directly to a file online then this is not the usage most tools have given them. People link to download pages. I think it’s more intuitive. The important thing is to get to the pages, people will know what to download from there. If you get linked to a file you won’t even know what you’re downloading, your browser will either ask you if you want to download this file or start downloading things. It’s better if people see some text before they decide to download something. Again , I think we’ve been catering to the 1% (i.e. conda, bio-whatever etc who want versioned files to point to).

I generated a list of entries (SQL rows) related to tools and their download info , filtering out entries that have download links that end in .zip and .gz, a crude filtering yes, but still shows that many entries have html-like urls for as download information.

Here is the link:
https://docs.google.com/spreadsheets/d/1cEvhSkC-J6rszEcOmuKFocHs4AxGfOhLNqBVZk0yI0o/edit?usp=sharing

My opinion is that if the current download urls should be specific for urls that point to files, then we are either using them wrong, or just using what we have because there isn’t an alternative. So perhaps we should create some sort of “general downloads page” or “Download instructions” or “Download description” etc.

**Comment by joncison** [comment]
Yeah, I think we need a "General downloads" or whatever.

The intention (with the other download types) was indeed to download an actual file, but I think this will come in more once we have a stable integration with projects like Biocontainers (container files), Debian (source and binary packages) etc. - so that these specific links can be maintained automatically (and with meaningful metadata that makes them actually useful)

So we agree, I think.

**Comment by joncison** [comment]
Now hotfixed in _bio.tools_  : "Downloads page"
