### ISSUE TITLE
Bio.Tools Collections: IDs and other attributes ...

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#33]
Other than numerous previous discussions in various groups, this issue is also supported by a request from [Alfred Pühler](mailto:puehler@cebitec.uni-bielefeld.de), the [coordinator of de.NBI](https://www.denbi.de/index.php/denbi-coordinator), from 30th June 2016. (See the next comment where the content of the request is pasted.)

It also relates to some of the changes towards version 2.0, sketched at the TWW Hackathon in May 2016 in Paris: https://docs.google.com/spreadsheets/d/1_KGr2DkulwtAjFJzNjTm08zXVphFlVZ8p29Id6XFlxc (sheets to the right of the first sheet).

My notes and suggestions to the de.NBI request, and our previous discussions, are the following:

We should include also a good possibility to identify 'Collections' within Bio.Tools. That would mean allowing at least 2 attributes for each collection: a display name, and an "ID name". These two could be the same, but could also be _e.g_. "de.NBI" and "denbi", respectively. That should then allow dereferencing a collection at _e.g._ https://bio.tools/denbi instead of just an unspecific full-text search of https://bio.tools/?q=de.NBI.

In addition, we should consider other optional attributes of collections, such as **description**(s), super-collections (collectionA **_isIncludedIn_** collectionB), **institutions**, **funding**, **credits**, _etc._
(I'm not sure about the collectionA **_isNewVersionOf_** collection, though. Although in a very special case it may make sense, _e.g._ if _Bioconductor_ would change its name to _BioCRAN_ :laughing:)

**Comment by matuskalas** [comment]
Citing [Alfred Pühler](mailto:puehler@cebitec.uni-bielefeld.de):

> beginning with this year, the service units of the German Network for
> Bioinformatics Infrastructure (de.NBI) started to register their
> services in the ELIXIR Tools and Data Services Registry. About 50% of
> de.NBI services are registered so far. As proposed in Freiburg by you,
> de.NBI services are tagged in the collection meta data element, such
> as those of the IPK in Gatersleben (de.NBI service unit GCBN):
> 
> https://bio.tools/?q=ipk
> 
> This tagging is used to retrieve and filter services by de.NBI service
> center or even partner (using affiliation), e.g. to dynamically
> generate service web sites:
> 
> http://www.ipk-gatersleben.de/en/bioinformatics-tools/
> 
> A comprehensive, list of all de.NBI services is available at the
> de.NBI homepage: http://www.denbi.de/index.php/services
> 
> In order to reflect de.NBI services as separate consortium but
> integrated into ELIXIR, we would like to ask you to check the
> possibility to create de.NBI subdomains on your web site. Examples
> from our point of view would be:
> 
> https://denbi.bio.tools [1]<https://denbi.bio.tools/> [1]
> 
> and also for dedicated service units: e.g.
> 
> https://gcbn.denbi.bio.tools <https://gcbn.denbi.bio.tools/> [2] and
> others accordingly.
> 
> Perhaps this would be on one hand a good possibility to improve the
> visibility of de.NBI in your reg-istry and on the other hand to helps
> us to promote your registry among the de.NBI users.
> 
> Many thanks for your help in advance. If there are any further
> questions don't hesitate to contact us.

**Comment by matuskalas** [comment]
## URLs:

I guess that URLs in form of https://bio.tools/denbi would in general be considered 'cooler URIs' (and especially more intuitive) among the Web community, compared to the form of https://denbi.bio.tools. But I also think it won't hurt to support both, if easy to set up.

For sub-collections, my gut feeling suggests that https://bio.tools/gcbn is more sustainable, maintainable, and more intuitive than https://bio.tools/denbi/gcbn or https://gcbn.denbi.bio.tools, as the membership in collections may dynamically change, and a collection may be a sub-collection in multiple super-collections. And, curators responsible for the two collections will typically be distinct.

In addition, in case it is of supreme importance, a (sub-)membership can be emphasised also in the name (and ID/URI) of a collection, _e.g._ "ELIXIR Norway" (https://bio.tools/elixir-norway) _**isIncludedIn**_ "ELIXIR" (https://bio.tools/elixir).

**Comment by joncison** [comment]
+1

Here we can have our cake and eat it:

https://bio.tools/provider/denbi
https://bio.tools/provider/gcbn    

: persistent URLs for a provider, resolving to a list of tools registered under that affiliation

https://denbi.bio.tools 
https://gcbn.bio.tools   

: subdomains for a contributor, with branding, resolving to a registry view pre-filtered to show tools registered under that affiliation (and possibly tools from all of its "parts")

yes, contributors (denbi and gcbn above) **must** be relatable so that we can say gcbn isIncludedIn deNBI etc.  From that we can get a very nice visualisation of the "contributors network"

**Comment by frederikcoppens** [comment]
I would opt for https://bio.tools/denbi rather then https://denbi.bio.tools. I find the former more emphasising it's a bio.tools subdomain, but that's personal taste I guess. Technically both are similar to implement (provided there is a wildcard certificate)

to indicate sub-membership I would not  use naming as these are not necessarily linked. If I look at my institute:
- PSB is a department of VIB      
- PSB is a group within UGent    
https://bio.tools/vib/psb and https://bio.tools/ugent/psb could indicate this

- For nodes https://bio.tools/elixir/elixir-belgium does have some redundancy in it, not sure if this is a problem

**Comment by matuskalas** [comment]
Re @joncison:

Then let's just do it in a simpler and more generic way, so that **every Collection** in Bio.Tools has an intuitive persistent cool URI & URL in form of http://bio.tools/collectionID, _e.g._ http://bio.tools/denbi, resolving to its details and the list of included records. Including the graph structure of "children" _Collections_.

And maybe they could be alternatively resolvable also from http://collectionID.bio.tools. (Can it be rewritten by _httpd_ if it's a DNS subdomain? Anybody? Ideally letting all http://xxx.bio.tools rewrite to http://bio.tools/xxx?) Although I don't understand why the form of http://xxx.bio.tools instead of the intuitive http://bio.tools/xxx could ever be useful to anyone. Please correct me if I'm wrong.

And every _Collection_ could then be allowed to have a logo, contacts, description, _etc_, or maybe even a customised colour scheme, if anybody would really like to set those up. The logos and colour schemes could then be "inheritable" via _**isIncludedIn**_, in every case when all "parent" _Collection_s have the same logo & scheme (transitively). 

"Provider" is too specific and won't match reality in many cases. Let's not repeat the same mistake as with the current "Affiliation".

_.../provider/..._ or _.../tool/..._ in both URIs and URLs are redundant and uncool. There shouldn't anyway ever be a _Collection_ with the same ID string as a _Tool_.

**Comment by matuskalas** [comment]
Re @frederikcoppens 
> I would opt for https://bio.tools/denbi rather then https://denbi.bio.tools. I find the former more emphasising it's a bio.tools subdomain, but that's personal taste I guess. Technically both are similar to implement (provided there is a wildcard certificate)

:+1: 

Re @frederikcoppens 
> 
> •PSB is a department of VIB
> 
> •PSB is a group within UGent
> 
> https://bio.tools/vib/psb and https://bio.tools/ugent/psb could indicate this
> 
> •For nodes https://bio.tools/elixir/elixir-belgium does have some redundancy in it, not sure if this is a problem

:-1:

I'm strongly against including any hierarchy into URIs, as it's not intuitive and not generic. A _Collection_|_Tool_ can be _**isIncludedIn**_ in multiple _Collection_s, and messing up **(then not) persistent** URIs with these **dynamic** relations which will change over time (people move, projects end, providers change, institutes rename) would be counterproductive for too many reasons: unintuitive URIs, non-persistent URIs, long URIs, uncool URIs.

**Comment by joncison** [comment]
Thanks a lot Matus & Frederik for the discussion here.

re "Although I don't understand why the form of http://xxx.bio.tools instead of the intuitive http://bio.tools/xxx could ever be useful to anyone. Please correct me if I'm wrong."

These two things can serve slightly different purposes.  People want "my bio.tools" i.e. a pre-filtered view over bio.tools showing only their tools, with branding.  The use of subdomains is part of the branding (arguably denbi.bio.tools has more brand identity than bio.tools/denbi)

In contrast, bio.tools/provider and/or bio.tools/collection (see below) can return information  about that provider or collection, i.e. a "provider card" or "collection card" in the same way as bio.tools/tool/ resolve to tool cards.

As for "provider" and "collection" these are different (but related concepts) : a "provider" is an entity (e.g. person, project, institute etc.) formally credited in a bio.tools entry.   A "collection" is merely a tag that anyone can add on any tool.  e.g. "Frederiks Favourite" is a collection but "VIB" is a provider.  

I agree use of "provider" is a bit clumsy; is "contributor" better?  By relating contributors, we can build an uber-cool contributors network, e.g. "Frederik" isIncludedIn PSB isIncludedIn VIB isIncludedIn ELIXIR-BE isIncludedIn Belgium  AND PSB includedIn UGent etc.

And yes, collections could be branded too, why not, if people wanted it.

I'm also against URL hierarchy mostly because volatility would mean these would not persist in long term.

Finally, sure we could also support bio.tools/ID where ID is a provider ID or tool ID (assuming we don't run in to too many clashes)

**Comment by joncison** [comment]
done in biotools-2.0-beta01

So far as biotoolsXSD goes, this is now supported: a <collection> element can specify a "biotools collectionID", currently defined by regex as one of : 

https://bio.tools/collection/collectionName
https://bio.tools/c/collectionName

but of course that can change.  the rest of this thread is more a concern of github.com/bio-tools/biotoolsregistry/.
