### ISSUE TITLE
doi syntax regex is too restrictive

### ISSUE THREAD

**Issue by hmenager** [bio-tools/biotoolsSchema#8]
The error below should not happen:

```
Element '{http://bio.tools}publicationsPrimaryID': [facet 'pattern'] The value '10.12688/f1000research.6924.1' is not accepted by the pattern '(doi:)?[0-9]{2}\.[0-9]{4}/.*'
```

The DOI mentioned above is legit, the second part of the DOI (registrant code) is not necessarily only 4 digits, see:
http://www.doi.org/doi_handbook/2_Numbering.html#2.2.2

**Comment by matuskalas** [comment]
The first part is always 10. That identifies the handle as DOI.
The second can be more than 4 digits, and even further sub-divided. Not sure about non-digit chars though, need to doublecheck more sources.

**Comment by joncison** [comment]
Googling for "regex DOI" is fun.  I'm going with this guys suggestion:
http://blog.crossref.org/2015/08/doi-regular-expressions.html

in XSD regex:
(doi:)?10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+

**Comment by jaanisoe** [comment]
The current regex is still too restrictive, because the DOI Handbook says that a DOI name "can incorporate any printable characters from the legal graphic characters of Unicode" (https://www.doi.org/doi_handbook/2_Numbering.html#2.2.1).

This is currently a problem only for 3 existing entries in bio.tools:
[10.1002/1615-9861(200102)1:2<340::AID-PROT340>3.0.CO;2-B](https://doi.org/10.1002/1615-9861(200102)1:2<340::AID-PROT340>3.0.CO;2-B)
[10.1002/(SICI)1522-2683(20000501)21:9<1694::AID-ELPS1694>3.0.CO;2-W](https://doi.org/10.1002/(SICI)1522-2683(20000501)21:9<1694::AID-ELPS1694>3.0.CO;2-W)
[10.1002/1097-0134(20001101)41:2<224::AID-PROT70>3.0.CO;2-Z](https://doi.org/10.1002/1097-0134(20001101)41:2<224::AID-PROT70>3.0.CO;2-Z)

All these DOIs are from Wiley, so maybe as the guy from Crossref says (in the post where the current regex was taken), the regex `10\.1002/[^\s]+` could be added as an additional pattern?

As a fun side note, Wiley is causing problems for themselves by making these "funny" DOIs. For example, as "<" and ">" are special characters in XML, I've seen problems with Wiley DOIs in PubMed and Europe PMC (double escaping). Also, in the following articles if you click on the DOI found below the publication title you will get "Not found" errors (probably because the "+" and "#" characters used in the DOI are special characters in URLs):
https://onlinelibrary.wiley.com/doi/full/10.1002/%28SICI%291097-0134%281999%2937%3A3%2B%3C66%3A%3AAID-PROT10%3E3.0.CO%3B2-K
https://onlinelibrary.wiley.com/doi/full/10.1002/1097-0231%2820000630%2914%3A12%3C1029%3A%3AAID-RCM984%3E3.0.CO%3B2-%23

There's another example, which is not from Wiley: the DOI corresponding to the [PMID 18720898](https://www.ncbi.nlm.nih.gov/pubmed/18720898) (present in https://bio.tools/QTL-ALL) is [10.3378/1534-6617(2008)80[99:ANGLST]2.0.CO;2](https://doi.org/10.3378/1534-6617(2008)80[99:ANGLST]2.0.CO;2). This DOI wouldn't pass the regex because of the square brackets "[" and "]".

Another side note, the DOI Handbook says that "The DOI syntax shall be made up of a DOI prefix and a DOI suffix separated by a forward slash.", so one small improvement that could be made to the current regex is the addition of an explicit `/` after `[0-9]{4,9}`.

Also, I guess the DOI regex is made more restrictive than the actual standard in order to catch potential mistakes. However, the most common mistake I've seen is a period (".") as the last character of the DOI (https://github.com/bio-tools/biotoolsLint/issues/5), which will pass the current regex (which is correct, as unfortunately it can't be ruled out that an actually valid DOI exists with a period at the end). Actually, the current regex would catch only 2 out of the 156 invalid DOIs I encountered, so maybe the DOI regex could be relatively lax (and catch really obvious mistakes like a space character in the DOI) and most invalid DOIs will be caught by trying to resolve them?

**Comment by joncison** [comment]
ok, wil take a second look

**Comment by joncison** [comment]
see https://www.crossref.org/blog/dois-and-matching-regular-expressions/

we had issues allowing regex with (erroneous) '.' (full stop) characters at end, see bio-tools/biotoolsRegistry#337

**Comment by joncison** [comment]
fd

**Comment by joncison** [comment]
fdf

**Comment by joncison** [comment]
@jaanisoe @hmenager @hansioan @matuskalas

I think I've improved things a bit.  The original regex was:
```(doi|DOI):?10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+"/>```

and now is:
```10\.[0-9]{4,9}/[\[\]&lt;&gt;A-Za-z0-9:;\)\(_/.-]+```

*i.e.*
* requirement for ```doi``` or ```DOI``` prefix gone
* ```/``` is enfoced after after ```[0-9]{4,9}```
* ```[``` and ```]``` are supported
* ```<``` and ```>``` are supported (done using ```&lt;``` and ```&gt``` as per XSD regex syntax - I think that's right) - *but* although XMLspy accepts such a regex, it doesn't think the supplied sample text (which includes ```<``` and ```>``` characters) is valid - I *think* this is a bug in XMLSpy

I could do with some independent checks / help here to get this any better

Thanks!

**Comment by joncison** [comment]
@jaanisoe once this is implemented in *bio.tools* a detailed check to see how things work out would be much appreciated cc @hansioan
