### ISSUE TITLE
Make collection ID fully match with the style of tool ID (and URI)

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#94]
As mentioned in https://github.com/bio-tools/biotoolsSchema/issues/79#issuecomment-306027592, it'll be great making the bio.tools collection IDs (and URIs) fully match with the tool IDs and URIs. As there are some further considerations that need to be (under)taken, I created this separate issue for that.

- [x] It'll be great to make the `collectionID` simple of type `biotoolsIdType`. Or update the `biotoolsCollectionIdType` to match. In either case, that is, making it match the same pattern (`[_a-zA-Z][_\-.0-9a-zA-Z]*`). Such pattern is necessary for enabling usage in RDF/XML (Linked Data). See #93 and https://github.com/bio-tools/biotoolsSchema/issues/79#issuecomment-306793420.

- [x] `xs:documentation` at https://github.com/bio-tools/biotoolsSchema/blob/753c572781d8d23a37eba2eb1d37a7728ec83b99/biotools_dev.xsd#L1112 will also need an adequate fix (and it should be maintained in `biotoolsIdType` or `biotoolsCollectionIdType`).

- [ ] It'll be really great to make the corresponding collection URIs resolve properly, too. That is http://bio.tools/{collectionID} resolving to what https://bio.tools/?page=1&collectionID=%27{collectionID}%27&sort=score returns nowadays.

**However:** _N.B._ that the collection IDs do (as opposed to tool IDs, assumingly) contain whitespaces, which have to be removed or even better replaced:

- [ ] I'd suggest replacement with underscores '_', as hyphens '-' are often used in their names (_e.g._ "ELIXIR-CZ"). Spaces are _e.g._ in "EBI Tools" and similar (in those the " Tools" could perhaps also be dropped(?); or for more safety replaced with 2 collections: "EBI" and "EBI_Tools").

**Yet another option** would be creating proper bio.tools records for collections, which could then for example have an **ID** _http://bio.tools/ebi_tools_ (or even _http://bio.tools/ebi_) and **short name** _EBI Tools_. This would enable adding _e.g._ **contacts** and a **homepage**. The bio.tools GUI should then also list the tools in the collection, as _https://bio.tools/?page=1&collectionID=%27EBI%20Tools%27&sort=score_ does nowadays. Notably, this would be an _**absolutely epic**_ solution to the "subdomains" (Reminder of the old discussion in #33).

**Comment by joncison** [comment]
My next commit will change ``collectionID`` type to ``biotoolsIdType``.  We'll need to check that the existing collection tags in bio.tools satisfy the new regex pattern (cc @hansioan - I'll create a new issue for this shortly).

The (now erroneous) ``xs:documentation`` comment is fixed.

Resolvable collection URIs would indeed by awesome!  @ekry,  @hansioan and I discussed this, and that we'll try to do this when the "contributor cards" (https://biotools.sifterapp.com/issues/432) are implemented, next year.  Metadata for collections and contributors can be handled in  very similar way.    In short, the plan is indeed to have proper bio.tools records for collections and contributors.

I tick the boxes above, because from the perspective of biotoolsSchema, the issues are closed.  By all means create issues in https://github.com/bio-tools/biotoolsregistry/issues for the corresponding features.
